# Generated by Django 4.0.2 on 2022-02-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.FloatField(verbose_name='Taille'),
        ),
    ]
