# Generated by Django 4.0.2 on 2022-02-10 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_alter_room_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name="Date d'entrée")),
                ('end_date', models.DateField(verbose_name='Date de sortie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
